sampling_rate: 44100
num_channels: 2
n_fft: 4096
window_length: 4096
hop_length: 1024
##############################################################
# generator
##############################################################
num_dual_path_blocks: 6
hidden_size_list: [4, 32, 64, 128]
band_SR: [0.225, 0.372, 0.403]
band_strides: [1, 4, 16]
band_kernels: [3, 4, 16]

##############################################################
# Discriminator
##############################################################
discriminator_stft_params:
  [[1024, 256, 1024], [2048, 512, 2048], [4096, 1024, 4096]]
discriminator_periods: [2, 3, 5, 7, 11]
mrd_loss_weight: 1.0
discriminator_activation: leakyrelu
##############################################################
# training
##############################################################
initial_step: 0
epochs: 200
batch_size: 4
patch_len: 44100 # 44100
cache_size: 250
spec_loss_weight: 20
feature_loss_weight: 2
generator_loss_weight: 1
discriminator_loss_type: "mse"
log_dir: ./logs/
mix_folder_path: "./Dataset/Processed"
piano_folder_path: "./Dataset/Processed"
instruments_folder_path: "./Dataset/Processed"
model_save_freq: 10000
epoch_max_steps: 10000
learning_rate_warmup_steps: 0
plot_interval_step: 10000
discriminator_update_prob: 0.33
discriminator_step_list: [400000, 1300000]
generator_step_list: [400000, 1300000]
